### ISSUE TITLE
Update PDF examples to latest health card spec version

### ISSUE THREAD

**Issue by christianpaquin** [smart-on-fhir/health-cards-designs#1]
It looks like the examples were generated following an older version of the SMART Health Card spec. The JWS payload uses `iat` instead of `nbf` (changed in v0.4.2), and the `vc` object contains a `@context` property (removed in v0.4.5).

**Comment by jpp9** [comment]
good catch. will fix this, and also match data contained within QRs with that on the pages, for completeness.

**Comment by jpp9** [comment]
fixed.

**Comment by christianpaquin** [comment]
The `smart_health_card_pdf_vaccine.pdf` and `smart_health_card_portal_vaccine.pdf` have been fixed, but it looks like the new mobile card `smart_health_card_portal_m_vaccine.pdf` has the same issue.
